spring:
  profiles:
    include:
      - db
      - file
      - aws

  servelet:
    multipart:
      enabled: true
      max-file-size: 200MB

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

cloud:
  aws:
    s3:
      bucket: dongdong-party
    region:
      static: ap-northeast-2