spring:
  profiles:
    include:
      - db
      - file

  servelet:
    multipart:
      enabled: true
      max-file-size: 200MB

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug