spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/dongdong
    username: sa
    password:
    driver-class-name: org.h2.Driver
  servelet:
    multipart:
      enabled: true
      max-file-size: 200MB

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

file:
  upload: '/Users/garden/Desktop/dongdong/server/src/main/resources/upload/image/' # 로컬 개발용